@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.mihayuniversal.heavencraft.block.angelfurnace;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;